### ISSUE TITLE
where is the dataset "train.conll","test.conll"....

### ISSUE THREAD

**Issue by SeekPoint** [ContextScout/gcn_ner#3]
train.conll

**Comment by fractalego** [comment]
Hi, thank you for your question.
We trained the system on the Ontonotes 5 corpus, which can be downloaded by subscribing to the LDC. The specific page is here https://catalog.ldc.upenn.edu/ldc2013t19

The dataset is free for non-commercial use, but it is not open source. We could not include it in our repo.

After you download the corpus, you can find three relevant directories in it: development/, test/, train/. In these directories there are many documents divided in folders, according to their origin. The files can be generated by using

cat <train_directory>/\*/\*.conll > train.conll
cat <dev_directory>/\*/\*.conll > dev.conll
cat <test_directory>/\*/\*.conll > test.conll

Hope this helps. Let me know if you need more info.

**Comment by weizier** [comment]
But after I've downloaded the corpus, called "ontonotes-release-5.0_LDC2013T19.tgz", there are not these three relevant directories in it, I just have those directories in it: '/data', '/docs', '/tools', 'index.html', and even in the directory '/data', there are just 'database' and 'files’. And moreover, I have located all the "*.conll" file, I couldn't find anything on my whole machine's disk. So, what's wrong with me? Thanks very much for any help or advice!

**Comment by fractalego** [comment]
Hi,
You are correct, there is a bit more work to do (apologies, it's been years since I did it)

You will need to follow the instruction found at this page:
http://cemantix.org/data/ontonotes.html

The script they provide will generate the "skeleton files". These are effectively conll files divided in the train, dev and test folders.

Let me know if you need more help.

**Comment by SeekPoint** [comment]
where can get ontonotes-release-5.0_LDC2013T19.tgz @weizier @fractalego

**Comment by fractalego** [comment]
The ontonotes files can be downloaded from here
https://catalog.ldc.upenn.edu/ldc2013t19

**Comment by ey4295** [comment]
@fractalego the link is missing now.can you please share it to me via email:ey4295@163.com

**Comment by anjiefang** [comment]
@fractalego Can you please share the data? 395421424@qq.com

**Comment by joczu** [comment]
> The ontonotes files can be downloaded from here
> https://catalog.ldc.upenn.edu/ldc2013t19

@fractalego Could you please share the ontonote data? 531902449@qq.com  thank you!

**Comment by fractalego** [comment]
Hi, the link is not missing: I really cannot share the data privately. I apologise for this but the data is copyrighted by the LDC.

My advice is to download it from the website: the data is free for non-commercial purposes
https://catalog.ldc.upenn.edu/LDC2013T19

Once you have the LDC data you can generate the conll files following the instruction from this site:
http://conll.cemantix.org/2012/data.html

This is how most people get the data. You can see it as a rite of passage for NLP :)
